---

- name: Install supervisor on Debian/Ubuntu
  apt:
    name: supervisor
    state: present
  when: ansible_os_family == 'Debian'

- name: Install supervisor on RedHat/CentOS
  yum:
    name: supervisor
    state: present
  when: ansible_os_family == 'RedHat'