groups:
  - name: InstanceDown
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critital
      annotations:
        summary: "监控实例:{{ $labels.instance }} 状态DOWN!"
        description: "监控Job组{{ $labels.job }}里的监控实例{{ $labels.instance }}状态变为DOWN!,请检查实例状态或者网络情况"
    - alert: MemoryAvaliableLow
      expr: ((node_memory_MemFree + node_memory_Buffers + node_memory_Cached) / node_memory_MemTotal) <= 0.1
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "Linux主机:{{ $labels.service_name }} 可用内存不足!"
        description: "Instance实例{{ $labels.instance }},机器可用内存3min内持续小于警戒线阀值,当前可用比率为:{{ $value }}."
    - alert: CPUsageHigh
      expr: (1 - avg by (hostname) (irate(node_cpu{mode="idle"}[3m]))) > 0.85
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "Linux主机:{{ $labels.service_name }} CPU使用率过高!"
        description: "Instance实例{{ $labels.instance }},机器CPU使用率3min内持续高于警戒线阀值,当前使用比率为:{{ $value }}."
    - alert: DiskUsageHigh
      expr: ((node_filesystem_size - node_filesystem_avail) / node_filesystem_size) >= 0.9
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "主机{{ $labels.service_name }}磁盘空间不足!"
        description: "主机实例{{ $labels.instance }},磁盘{{ $labels.device }}挂载点:{{ $labels.mountpoint }}可用空间不足,当前使用比率为:{{ $value }}"