groups:
  - name: InstanceDown
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critital
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

    - alert: MemoryAvaliableLow
      expr: ((node_memory_MemFree + node_memory_Buffers + node_memory_Cached) / node_memory_MemTotal) <= 0.16
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Server {{ $labels.hostname }} Memory Avaliable is dangerously low"
        description: "This Instance {{ $labels.instance }} Memory Avaliable is under the thread with a value of {{ $value }}."

    - alert: CPUsageHigh
      expr: (1 - avg by (hostname) (irate(node_cpu{mode="idle"}[3m]))) > 0.84
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Server {{ $labels.hostname }} CPU Usage is dangerously high"
        description: "This Instance {{ $labels.instance }} CPU Usage has exceeded the threshold with a value of {{ $value }}."
    - alert: DiskUsageHigh
      expr: ((node_filesystem_size - node_filesystem_avail) / node_filesystem_size) >= 0.86
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "Server {{ $labels.hostname }} Disk device {{ $labels.device }} Usage is dangerously high"
        description: "This Instance {{ $labels.instance }} Disk Usage has exceeded the threshold with a value of {{ $value }}"