---

- name: create alertmanager install path
  file:
    path: "{{ prometheus_install_path }}"
    mode: 0755
    state: directory

- name: download alertmanager into install path
  get_url:
    url: "{{ alertmanager_download_url }}"
    dest: "{{ prometheus_install_path }}"
    checksum: sha256:{{ alermanager_checksum }}

## If you env can't out of internet use copy module, otherwise use the above task.
#- name: copy alertmanager package into your install path
#  copy:
#    src: alertmanager-0.14.0.linux-amd64.tar.gz
#    dest: "{{ prometheus_install_path }}"

- name: unzip alertmanager package
  shell: cd "{{ prometheus_install_path }}" && tar -zxf "alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"

- name: copy alermanager config file
  template:
    src: alertmanager.yml
    dest: "{{ alertmanager_path }}"
    mode: 0644
    owner: root

- name: copy supervisor alertmanager conf file On 'Debian' Family
  template:
    src: alertmanager_supervisor.conf
    dest: /etc/supervisor/conf.d/
    owner: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: copy supervisor alertmanager conf file On 'RedHat' Family
  template:
    src: alertmanager_supervisor.conf
    dest: /etc/supervisor/conf.d/
    owner: root
    mode: 0644
  when: ansible_os_family == 'RedHat'


- name: supervisor reread alertmanager
  supervisorctl:
    name: alertmanager
    state: present
# When state = present, the module will call supervisorctl reread then supervisorctl add if the program/group does not exist.

- name: supervisor update and restart alertmanager
  supervisorctl:
    name: alertmanager
    state: restarted
# When state = restarted, the module will call supervisorctl update then call supervisorctl restart.

- name: delete alertmanager package
  file:
    path: "{{ prometheus_install_path }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"
    state: absent
