global:
  scrape_interval: 15s
  scrape_timeout: 15s
  # How frequently to evaluate rules. default = 1m
  evaluation_interval: 1m
  external_labels:
    monitor: ops-monitor01
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - '{{ alertmanager_url }}'
rule_files:
  - '{{ prometheus_server_path }}/alert.yml'
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: node-exporter
    static_configs:
      - targets: ['10.16.1.1:9100']
        labels:
          hostname: 'HostTest'

#  - job_name: 'node-discovery'
#    consul_sd_configs:
#      - server: '172.30.100.45:8500'
#        services: ['node_exporter']
#    relabel_configs:
#    - source_labels: ['__meta_consul_service_id']
#      #regex: '(.*)'
#      target_label: 'hostname'
#      #replacement: '$1'

#  - job_name: 'lnode-discorvery'
#    file_sd_configs:
#      - files:
#        - '{{ prometheus_server_path }}/conf.d/lnode-discovery.json'

#  - job_name: 'service-discorvery'
#    scrape_interval: 60s
#    scrape_timeout: 30s
#    file_sd_configs:
#      - files:
#        - '{{ prometheus_server_path }}/conf.d/service-discovery.json'
